// packages/web/services/fileHandlerService.ts

import { DocumentService } from './documentService';

/**
 * Service to handle file operations like downloading and previewing
 * In a real app, this would interact with your backend API
 */
class FileHandlerServiceClass {
  
  /**
   * Get actual file content from storage
   */
  async getFileContent(document: any): Promise<string | undefined> {
    // First try to get from DocumentService (for uploaded files)
    const storedContent = await DocumentService.getFileContent(document.id);
    if (storedContent) {
      return storedContent;
    }
    
    // For mock documents without stored content, generate sample
    return this.generateSampleContent(document);
  }

  /**
   * Generate sample content for mock documents
   */
  private generateSampleContent(document: any): string {
    const { fileType, title, description } = document;
    
    if (fileType.includes('pdf')) {
      return this.generateSamplePDF(title, description);
    } else if (fileType.includes('word') || fileType.includes('document')) {
      return this.generateSampleHTML(title, description, 'Word Document');
    } else {
      return this.generateSampleText(title, description);
    }
  }

  /**
   * Generate a downloadable blob from content
   */
  async generateFileContent(document: any): Promise<Blob> {
    // Try to get actual content first
    const actualContent = await this.getFileContent(document);
    
    if (!actualContent) {
      throw new Error('File content not found');
    }
    
    // Check if content is a data URL (starts with data:)
    if (actualContent.startsWith('data:')) {
      // Convert data URL to blob
      return this.dataURLToBlob(actualContent);
    }
    
    // Otherwise, create blob from text content
    return new Blob([actualContent], { type: document.fileType });
  }

  /**
   * Convert data URL to Blob
   */
  private dataURLToBlob(dataURL: string): Blob {
    const arr = dataURL.split(',');
    const mime = arr[0].match(/:(.*?);/)?.[1] || 'application/octet-stream';
    const bstr = atob(arr[1]);
    let n = bstr.length;
    const u8arr = new Uint8Array(n);
    
    while (n--) {
      u8arr[n] = bstr.charCodeAt(n);
    }
    
    return new Blob([u8arr], { type: mime });
  }

  /**
   * Generate a sample HTML content for Word documents
   */
  private generateSampleHTML(title: string, description: string, docType: string): string {
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
    h1 { color: #ff6633; }
    .container { max-width: 800px; margin: 0 auto; }
    .header { border-bottom: 2px solid #ff6633; padding-bottom: 20px; margin-bottom: 30px; }
    .content { background: #f9f9f9; padding: 30px; border-radius: 8px; }
    .footer { margin-top: 40px; text-align: center; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>${title}</h1>
      <p><strong>Type:</strong> ${docType}</p>
      <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
    </div>
    <div class="content">
      <h2>Document Content</h2>
      <p>${description || 'No description provided.'}</p>
      
      <h3>Sample Content</h3>
      <p>This is a sample ${docType} generated for demonstration purposes.</p>
      <p>In a production environment, this would be the actual uploaded file content.</p>
      
      <ul>
        <li>Item 1: Learning objectives</li>
        <li>Item 2: Key concepts</li>
        <li>Item 3: Practice exercises</li>
        <li>Item 4: Additional resources</li>
      </ul>
      
      <p>The actual document would contain the real learning materials uploaded by the mentor.</p>
    </div>
    <div class="footer">
      <p>Generated by DMIF Student Tracker</p>
    </div>
  </div>
</body>
</html>
    `;
  }

  /**
   * Generate a sample PDF-like content (as string, not Uint8Array)
   */
  private generateSamplePDF(title: string, description: string): string {
    // Return a simple string representation
    return `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> /MediaBox [0 0 612 792] /Contents 5 0 R >>
endobj
4 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
5 0 obj
<< /Length 44 >>
stream
BT /F1 24 Tf 100 700 Td (${title}) Tj ET
BT /F1 12 Tf 100 650 Td (${description || 'No description'}) Tj ET
endstream
endobj
xref
0 6
0000000000 65535 f 
0000000010 00000 n 
0000000056 00000 n 
0000000111 00000 n 
0000000212 00000 n 
0000000277 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
382
%%EOF`;
  }

  /**
   * Generate sample text content
   */
  private generateSampleText(title: string, description: string): string {
    return `
${title}
${'='.repeat(title.length)}

Generated: ${new Date().toLocaleString()}
Type: Text Document

DESCRIPTION
${description || 'No description provided.'}

CONTENT
This is a sample text document generated for demonstration purposes.
In a production environment, this would be the actual uploaded file content.

The document contains the following sections:
1. Learning Objectives
2. Key Concepts
3. Practice Exercises
4. Additional Resources
5. References

---
Generated by DMIF Student Tracker
    `;
  }

  /**
   * Download a file
   */
  async downloadFile(document: any): Promise<void> {
    try {
      // Generate file content
      const blob = await this.generateFileContent(document);
      
      // Create download link
      const url = window.URL.createObjectURL(blob);
      const link = window.document.createElement('a');
      link.href = url;
      link.download = document.fileName || `${document.title}.${this.getFileExtension(document.fileType)}`;
      
      // Trigger download
      window.document.body.appendChild(link);
      link.click();
      
      // Clean up
      window.document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
      
      return Promise.resolve();
    } catch (error) {
      console.error('Error downloading file:', error);
      return Promise.reject(error);
    }
  }

  /**
   * Get file extension from MIME type
   */
  private getFileExtension(mimeType: string): string {
    const extensions: Record<string, string> = {
      'application/pdf': 'pdf',
      'application/msword': 'doc',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'docx',
      'text/plain': 'txt',
      'text/html': 'html',
      'image/jpeg': 'jpg',
      'image/png': 'png',
    };
    
    return extensions[mimeType] || 'bin';
  }

    /**
     * Get a preview URL for a document
     */
    async getPreviewUrl(document: any): Promise<string> {
    try {
        // Try to get actual file content
        const content = await this.getFileContent(document);
        
        if (content) {
        if (content.startsWith('data:')) {
            // If it's already a data URL, use it directly
            return content;
        } else {
            // Otherwise create a blob URL
            const blob = new Blob([content], { type: document.fileType });
            return window.URL.createObjectURL(blob);
        }
        }
    } catch (error) {
        console.error('Error getting actual content, falling back to sample:', error);
    }
    
    // Fallback to sample content based on file type
    if (document.fileType.includes('pdf')) {
        const blob = await this.generateFileContent(document);
        return window.URL.createObjectURL(blob);
    }
    
    if (document.fileType.includes('image')) {
        // Return a placeholder image
        return 'https://via.placeholder.com/800x600.png?text=Image+Preview';
    }
    
    if (document.fileType.includes('word') || document.fileType.includes('document')) {
        // For Word docs, create an HTML preview that explains how to view
        const htmlContent = this.createWordPreviewHTML(document);
        const blob = new Blob([htmlContent], { type: 'text/html' });
        return window.URL.createObjectURL(blob);
    }
    
    if (document.fileType.includes('text')) {
        // For text files, show the content
        const blob = await this.generateFileContent(document);
        return window.URL.createObjectURL(blob);
    }
    
    // Default fallback
    const htmlContent = this.createGenericPreviewHTML(document);
    const blob = new Blob([htmlContent], { type: 'text/html' });
    return window.URL.createObjectURL(blob);
    }

    /**
     * Create a helpful HTML preview for Word documents
     */
    private createWordPreviewHTML(document: any): string {
    return `
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="UTF-8">
    <title>${document.title} - Word Document Preview</title>
    <style>
        body { 
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif; 
        margin: 0; 
        padding: 20px; 
        background: #f5f5f5;
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        }
        .container {
        max-width: 600px;
        background: white;
        border-radius: 12px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        padding: 40px;
        text-align: center;
        }
        .icon {
        width: 80px;
        height: 80px;
        background: #e6f0ff;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        margin: 0 auto 24px;
        }
        .icon svg {
        width: 40px;
        height: 40px;
        fill: #2563eb;
        }
        h1 {
        font-size: 24px;
        color: #1a1a1a;
        margin-bottom: 8px;
        }
        .filename {
        color: #666;
        font-size: 14px;
        margin-bottom: 24px;
        word-break: break-all;
        }
        .info {
        background: #f8f9fa;
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 24px;
        text-align: left;
        }
        .info p {
        margin: 8px 0;
        color: #444;
        font-size: 14px;
        }
        .info strong {
        color: #1a1a1a;
        display: inline-block;
        width: 100px;
        }
        .button {
        display: inline-flex;
        align-items: center;
        padding: 12px 24px;
        background: #2563eb;
        color: white;
        text-decoration: none;
        border-radius: 8px;
        font-weight: 500;
        transition: background 0.2s;
        border: none;
        cursor: pointer;
        font-size: 16px;
        }
        .button:hover {
        background: #1d4ed8;
        }
        .button.secondary {
        background: white;
        color: #2563eb;
        border: 1px solid #2563eb;
        margin-left: 12px;
        }
        .button.secondary:hover {
        background: #f0f7ff;
        }
        .note {
        margin-top: 24px;
        color: #888;
        font-size: 12px;
        }
    </style>
    </head>
    <body>
    <div class="container">
        <div class="icon">
        <svg viewBox="0 0 24 24">
            <path d="M14 2H6c-1.1 0-1.99.9-1.99 2L4 20c0 1.1.89 2 1.99 2H18c1.1 0 2-.9 2-2V8l-6-6zm2 16H8v-2h8v2zm0-4H8v-2h8v2zm-3-5V3.5L18.5 9H13z"/>
        </svg>
        </div>
        
        <h1>${document.title}</h1>
        <div class="filename">${document.fileName}</div>
        
        <div class="info">
        <p><strong>Type:</strong> Microsoft Word Document</p>
        <p><strong>Size:</strong> ${this.formatFileSize(document.fileSize)}</p>
        <p><strong>Uploaded:</strong> ${new Date().toLocaleDateString()}</p>
        </div>
        
        <p style="margin-bottom: 24px; color: #666;">
        Word documents cannot be previewed directly in the browser. 
        Please download the file to view its content.
        </p>
        
        <div>
        <button onclick="window.parent.downloadFile()" class="button">
            <svg style="width: 18px; height: 18px; margin-right: 8px;" viewBox="0 0 24 24">
            <path fill="currentColor" d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z"/>
            </svg>
            Download Document
        </button>
        </div>
        
        <div class="note">
        After downloading, open the file with Microsoft Word or compatible software.
        </div>
    </div>

    <script>
        function downloadFile() {
        window.parent.postMessage('download', '*');
        }
    </script>
    </body>
    </html>
    `;
    }

    /**
     * Create a generic preview HTML
     */
    private createGenericPreviewHTML(document: any): string {
    return `
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="UTF-8">
    <title>${document.title} - Preview</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; text-align: center; }
        .message { color: #666; margin: 40px; }
    </style>
    </head>
    <body>
    <h1>${document.title}</h1>
    <p class="message">Preview not available for this file type.</p>
    <p>Please download the file to view its content.</p>
    </body>
    </html>
    `;
    }

    // Add formatFileSize helper
    private formatFileSize(bytes: number): string {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
    }
}

export const FileHandlerService = new FileHandlerServiceClass();